truck_api/urls.py
from django.urls import path

from truck_api.views import TruckListApiView, TruckDetailsApiView

urlpatterns = [
    path('', TruckListApiView.as_view(), name='truck list api'),
    path('<int:pk>/', TruckDetailsApiView.as_view(), name='truck details api')
]

truck_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

media_files = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('truck/', include('truck_app.urls')),
    path('accounts/', include('truck_auth.urls')),
    path('truck-api/', include('truck_api.urls')),
    path('rest-api/', include('rest_framework.urls')),

] + media_files

truck_app/models.py
from django.contrib.auth.models import User
from django.db import models
from truck_app.validators import validator_comment_end, validator_price_is_digit


# Create your models here.
class Truck(models.Model):
    nickname = models.CharField(max_length=20)
    make = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    description = models.TextField(max_length=400)
    image = models.ImageField(upload_to='public/images')
    price = models.CharField(max_length=10, validators=(validator_price_is_digit,))
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nickname}'

    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)


class Comment(models.Model):
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)
    text = models.CharField(blank=False, max_length=100, validators=(validator_comment_end,))
    time = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.truck}'


class Like(models.Model):
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.truck}'

templates/user/login.html
{% extends 'shared/base.html' %}

{% block auth_h1 %}
    LogIn
{% endblock %}

{% block auht_base %}
    <div class="container`">
        <form style="opacity: 80%" class="col-lg-6 offset-lg-3" method="POST" action="{% url 'login user' %}">
            {% csrf_token %}
            <h6 style="color: white">{{ form.errors }}</h6>
            <div class="form-group">

                <label for="nickname" style="color: aliceblue">Username</label>
                {{ form.username }}

                <label for="make" style="color: aliceblue">Password</label>
                {{ form.password }}

            </div>
            <input type="submit" value="LogIn" class="btn btn-dark btn-lg">
            <a class="btn btn-dark" href="javascript:history.back()">Back</a>
        </form>
    </div>
{% endblock %}

templates/user/logout.html
{% extends 'shared/base.html' %}

{% block h1_content %} LogOut {% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 style="color: white">Are you sure you want to LOGOUT ?</h1>
                <div class="m-auto d-flex justify-content-center">
                    <div class="m-2">
                        <form method="post" action="{% url 'logout user' %}">
                            {% csrf_token %}
                            <input type="submit" value="LogOut" class="btn btn-dark"/>
                        </form>
                    </div>
                    <div class="m-2">
                        <a class="btn btn-dark btn-lg" href="javascript:history.back()">No, go back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile.html
{% extends 'shared/base.html' %}

{% block h1_content %}
    Hello, {{ user.username }}!
{% endblock %}

{% block base_content %}

    <div class="container">
        <div class="w-50 m-auto">
            <form style="opacity: 80%" class="col-lg-6 offset-lg-3" method="POST" action="{% url 'profile user' %}">
                {% csrf_token %}
                <h6 style="color: white">{{ form.phone_number.errors }}</h6>
                <div class="form-group">
                    <label for="nickname" style="color: aliceblue">Phone number</label>
                    {{ form.phone_number }}
                    <label for="make" style="color: aliceblue">City</label>
                    {{ form.city }}
                </div>
                <input type="submit" value="Edit" class="btn btn-dark">
                <a class="btn btn-dark" href="{% url 'home page' %}">Back</a>
            </form>
        </div>
        <hr>
        {% if trucks %}
            <h2 class='text-center' style="color: white">Your Trucks</h2>
            <div class="row" style="opacity: 80%">
                {% for truck in trucks %}
                    <div class="card m-3"
                         style="width: 30rem; background: url({{ truck.image.url }}); background-size: 150%;">
                        <div class="card-body">
                            <h4 class="card-title">{{ truck.make }} {{ truck.model }},
                                /Likes: {{ truck.like_set.count }}/</h4>
                            <h5 class="card-text">Price: {{ truck.price }} $</h5>
                            <a href="{% url 'details page' truck.id %}" class="btn btn-dark">Details</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center" style="color: white">
                <h2>No Trucks</h2>
                <a href="{% url 'create page' %}" class="btn btn-dark btn-lg">Add First Truck</a>
            </div>
        {% endif %}
    </div>

{% endblock %}

templates/user/register.html
{% extends 'shared/base.html' %}

{% block auth_h1 %}
    Register
{% endblock %}

{% block auht_base %}
    <div class="container`">
        <form style="opacity: 80%" class="col-lg-6 offset-lg-3" method="POST" action="{% url 'register user' %}">
            {% csrf_token %}
            <h6 style="color: white">{{ form.errors }}</h6>
            <div class="form-group">

                <label for="nickname" style="color: aliceblue">Username</label>
                {{ form.username }}

                <label for="make" style="color: aliceblue">Password</label>
                {{ form.password1 }}

                <label for="make" style="color: aliceblue">Confirm Password</label>
                {{ form.password2 }}

            </div>
            <input type="submit" value="Register" class="btn btn-dark btn-lg">
            <a class="btn btn-dark" href="javascript:history.back()">Back</a>
        </form>
    </div>
{% endblock %}